### ISSUE TITLE
Issues with Demo Project & Personal .

### ISSUE THREAD

**Issue by rjkenefick** [enebin/Aespa#1]
Looking forward to using this , but having some issues with some errors within the demo project & also my implementation within my own project .

1st . Demo Project  SettingsView

- First and majority of build errors I am getting seem to be related with the contentViewModel call being able to throw and isn't marked with try leaving the error not being handled.  

-  Getting an error that the Value AespaSession has no member of captureSession & also isMuted

- Lastly the package in order to run the app is also missing from the project structure I see the folder but its empty might be an issue on my part lol . 

2nd . myProject 

- when calling the VideoContentView from a button to bring up the camera seems to be freezing on the startup leaving view of the camera frozen .

- Looking at the debugger any time a button or view is changed I am getting a log "[Aespa] Session configured successfully"  every time this call happens the performance of the app diminishes , this could be the lack of my understanding of the library or how I am using it lol.

**Comment by rjkenefick** [comment]
After some workarounds I was able to get the camera working in both my personal project and the demo with some of your recommended changes so thank you ! ,  Im currently running into a couple of errors that seem to occur on both projects when it comes to recording and saving the video , I am able to record 1-2 videos and seems to be saving to my phones library correctly , but usually after the first I get the errors below  causing  the camera stop being able to record videos and must completely close out of the app in order to record a video again . Apologies in advance I am still new to learning swift/swiftUI lol .

Aespa-iOS[2580:744265] [core] "Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""
I would normally assume this is due to not having the correct Privacy notices active in the Plist , but I've made sure I have all correct ones  active ( microphone Usage , Photo library usage , Camera Usage ) ect...  This is completely a shot in the dark from some of issues Ive seen from looking up the error seem to point to using Photos .


2023-06-11 11:23:03.460491-0700 Aespa-iOS[2580:744259] [PAAccessLogger] Failed to log access with error: access=<PATCCAccess 0x280a94d70>  again not sure exactly what this is but from looking up the error seems to point to accessing a users photo albums .


I hope this helps !

**Comment by enebin** [comment]
Thank you. Please feel free to post an issue whenever there is a problem again 👏
