### ISSUE TITLE
-[AVCaptureConnection setVideoOrientation:] Not supported - use -isVideoOrientationSupported

### ISSUE THREAD

**Issue by BabyGeek** [enebin/Aespa#24]
Hi, I am encountering an issue where when I try to do a video using the front camera, I got this error:

```swift
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureConnection setVideoOrientation:] Not supported - use -isVideoOrientationSupported'
```

It seems like this error occurs because the Session in AespaOption has `autoVideoOrientationEnabled` set to `true` however there is no solution to set it to false, it makes my app crash and not usable, any ideas?

I am using Aespa v0.3.1 with SPM
Also happens on latest 0.4.0 version..

**Comment by enebin** [comment]
Hi @BabyGeek , thank you for raising the issue. 
I've discovered that the option property you mentioned was set to `internal`, so I've changed it to `public`. 
Could you please check out the latest version(0.4.1) and see if the same problem occurs?"

**Comment by BabyGeek** [comment]
@enebin I just updated and I was able to edit the session option, it seems to work properly now, thank you for the quick update 🎉

**Comment by enebin** [comment]
Great! If you encounter any other issues in the future, please feel free to raise them. Your contributions are always welcome!

**Comment by BabyGeek** [comment]
@enebin I was a bit too fast, it seems like first opening of my camera works, if I close it and reopen it, the error comes back

**Comment by enebin** [comment]
@BabyGeek  I see. I will check it again on my end as well. It would be helpful if you could provide more details about the error situation!

**Comment by BabyGeek** [comment]
It seems like the error is triggered by using the modifier `.orientation(to: .portrait)` on my session configuration

**Comment by BabyGeek** [comment]
@enebin Sure, the error message is still the same 

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureConnection setVideoOrientation:] Not supported - use -isVideoOrientationSupported'
```

When I comment `.orientation(to: .portrait)` in my configuration

```
        aespaSession
            .focus(mode: .continuousAutoFocus)
            .changeMonitoring(enabled: true)
            .position(to: position)
            .orientation(to: .portrait)
            .quality(to: .high)
```

The error does not display, however when it is not commented the error does not display at first load, but display and crash at second load of the camera view I use (It's a view that open's and close by using buttons)

**Comment by enebin** [comment]
and can I get the version of iOS you're using?

**Comment by BabyGeek** [comment]
I am using version 17.1.1

**Comment by enebin** [comment]
Hi, @BabyGeek! Sorry for the late reply. 

From the problem you're experiencing, it seems like the app you're developing is unable to `setVideoOrientation` due to some reason, and attempting to use it anyway is causing an error. Therefore, I've added a `guard` clause to check the availability. 

Unfortunately, I can't replicate the error on my end, so I'm not sure of the exact cause. Please let me know if the error occurs again.
