### ISSUE TITLE
Cant use all AespaOption initializers

### ISSUE THREAD

**Issue by fiebiger** [enebin/Aespa#42]
I'm trying use this public Init for the AespaOption
` public init(asset: Asset, session: Session, log: Log) `

But Asset, Log and Session are not accessible due to their 'internal' protection level.

Also AespaCoreSession doesn't take into account the cameraDevicePreference when initializing the video preview on `func addMovieInput() throws`

**Comment by enebin** [comment]
It's fixed in the latest version, `0.5.3`. Sorry for inconvenient.
